"""add email_notifications_enabled to users

Revision ID: 0c370dd61c62
Revises: 75e4d2810a63
Create Date: 2026-08-22 09:14:14.762844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c370dd61c62'
down_revision: Union[str, None] = '75e4d2810a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('users', 'email_notifications_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    # ### end Alembic commands ###
