"""add avatar_url to researchers

Revision ID: 32a5ee870ff7
Revises: 0c370dd61c62
Create Date: 2026-08-23 10:05:04.109638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a5ee870ff7'
down_revision: Union[str, None] = '0c370dd61c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchers', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researchers', 'avatar_url')
    # ### end Alembic commands ###
