import { useState } from "react";
import { FaEye, FaEyeSlash, FaKey } from "react-icons/fa";
import { Link, useNavigate } from "react-router-dom";
import { confirmPasswordReset, requestPasswordReset } from "../services/authService";
import "../styles/login.css";

function ForgotPassword() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [sent, setSent] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false);
  const validEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
  const request = async (event) => { event.preventDefault(); setError(""); if (!email.trim()) return setError("Please enter your email address."); if (!validEmail(email)) return setError("Please enter a valid email address."); setBusy(true); try { setMessage((await requestPasswordReset(email)).message); setSent(true); } catch (e) { setError(e.response?.data?.detail || "Could not send reset code."); } finally { setBusy(false); } };
  const reset = async (event) => { event.preventDefault(); setError(""); if (code.length !== 6) return setError("Enter the six-digit reset code."); if (password.length < 8) return setError("Password must be at least 8 characters long."); if (!/[^A-Za-z0-9\s]/.test(password)) return setError("Password must contain at least one special character."); if (password !== confirmPassword) return setError("Passwords do not match."); setBusy(true); try { setMessage((await confirmPasswordReset(email, code, password)).message); window.setTimeout(() => navigate("/"), 1400); } catch (e) { setError(e.response?.data?.detail || "Could not reset password."); } finally { setBusy(false); } };
  return <main className="login-container"><section className="login-card"><div className="logo"><FaKey /></div><h1 className="title">{sent ? "Reset Password" : "Forgot Password?"}</h1><p className="subtitle">{sent ? "Enter the code from your email and choose a new password." : "Enter your registered email address and we'll help you reset your password."}</p><form onSubmit={sent ? reset : request}><div className="input-group"><label>Email</label><div className="input-box"><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} disabled={sent} /></div></div>{sent && <><div className="input-group"><label>Reset code</label><div className="input-box"><input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} placeholder="123456" /></div></div><div className="input-group"><label>New password</label><div className="input-box"><input required type={showPassword ? "text" : "password"} minLength="8" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="password-toggle" type="button" onClick={() => setShowPassword((value) => !value)} aria-label="Show or hide new password">{showPassword ? <FaEyeSlash /> : <FaEye />}</button></div><p className="password-hint">At least 8 characters and one special symbol.</p></div><div className="input-group"><label>Confirm new password</label><div className={`input-box ${confirmPassword && confirmPassword !== password ? "input-box--error" : ""}`}><input required type={showConfirm ? "text" : "password"} autoComplete="new-password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /><button className="password-toggle" type="button" onClick={() => setShowConfirm((value) => !value)} aria-label="Show or hide confirmation password">{showConfirm ? <FaEyeSlash /> : <FaEye />}</button></div>{confirmPassword && confirmPassword !== password && <p className="field-error">Passwords do not match.</p>}</div></>}{(message || error) && <div className={`auth-message auth-message--${error ? "error" : "success"}`} role="alert"><strong>{error ? "Please check your details" : "Password reset instructions"}</strong><span>{error || message}</span></div>}<button className="login-btn" disabled={busy}>{busy ? "Please wait..." : sent ? "Reset password" : "Send reset code"}</button></form><p className="register-text"><Link to="/">← Back to Login</Link></p></section></main>;
}
export default ForgotPassword;
