const conferenceState = { rows: [] };
const byId = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>\"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#039;"}[char]));
const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString(undefined, {year:"numeric", month:"short", day:"numeric"}) : "Date to be announced";
function showConferenceError(message) { byId("errorMessage").textContent = message; byId("errorMessage").classList.add("show"); }
async function loadConferenceStats() { const response = await apiFetch("/conferences/stats"); if (!response) throw new Error("Please log in to view conferences."); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || `Conference statistics request failed (${response.status}).`); byId("totalConferences").textContent = data.total_conferences ?? 0; byId("upcoming").textContent = data.upcoming ?? 0; byId("completed").textContent = data.completed ?? 0; byId("totalParticipants").textContent = Number(data.total_participants ?? 0).toLocaleString(); }
function renderConferences() { const grid = byId("conferenceGrid"); const rows = conferenceState.rows; byId("resultCount").textContent = `${rows.length} result${rows.length === 1 ? "" : "s"}`; if (!rows.length) { grid.innerHTML = '<div class="empty">No conferences match these filters.</div>'; return; } grid.innerHTML = rows.map((conference) => `<article class="conference-card ${conference.status.toLowerCase()}"><div class="card-top"><span class="badge ${conference.status.toLowerCase() === "completed" ? "completed" : ""}">${escapeHtml(conference.status)}</span><span class="badge">${escapeHtml(conference.field || "General")}</span></div><h3>${escapeHtml(conference.name)}</h3><p class="card-description">${escapeHtml(conference.description || conference.organizer || "Academic conference")}</p><div class="meta">📍 ${escapeHtml(conference.location || "Location to be announced")}<br>📅 ${formatDate(conference.start_date)}${conference.end_date ? ` - ${formatDate(conference.end_date)}` : ""}</div><div class="card-footer"><div><strong>${escapeHtml(conference.organizer || "-")}</strong><small>Organizer</small></div>${conference.website ? `<a class="details" href="${escapeHtml(conference.website)}" target="_blank" rel="noreferrer">Website →</a>` : ""}</div></article>`).join(""); }
async function loadConferences() { const params = new URLSearchParams(); const search = byId("search").value.trim(); if (search) params.set("search", search); if (byId("field").value !== "all") params.set("field", byId("field").value); if (byId("status").value !== "all") params.set("status", byId("status").value); params.set("sort", byId("sort").value); const response = await apiFetch(`/conferences/?${params}`); if (!response) throw new Error("Please log in to view conferences."); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || `Conference request failed (${response.status}).`); conferenceState.rows = data; renderConferences(); }
async function initConferencePage() { try { const user = await getCurrentUser(); updateUserProfile(user); await Promise.all([loadConferenceStats(), loadConferences()]); const fields = [...new Set(conferenceState.rows.map((row) => row.field).filter(Boolean))].sort(); byId("field").insertAdjacentHTML("beforeend", fields.map((field) => `<option>${escapeHtml(field)}</option>`).join("")); } catch (error) { showConferenceError(error.message); } }
["search","field","status","sort"].forEach((id) => byId(id).addEventListener("input", loadConferences)); byId("globalSearch").addEventListener("input", () => { byId("search").value = byId("globalSearch").value; loadConferences(); }); byId("addConference").addEventListener("click", () => byId("conferenceDialog").showModal()); document.querySelector("[data-close]").addEventListener("click", () => byId("conferenceDialog").close()); byId("conferenceForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const payload = Object.fromEntries(form.entries()); ["description","organizer","location","start_date","end_date","field","website"].forEach((key) => { if (!payload[key]) delete payload[key]; }); try { const response = await apiFetch("/conferences/", {method:"POST", body:JSON.stringify(payload)}); const data = await readJson(response); if (!response.ok) throw new Error(data.detail || "Unable to save conference."); byId("conferenceDialog").close(); event.target.reset(); await Promise.all([loadConferenceStats(), loadConferences()]); } catch (error) { byId("formError").textContent = error.message; byId("formError").classList.add("show"); } }); initConferencePage();